Repository SpiderLabs/owasp-modsecurity-crs, pull requests merged in 2018-12, with the labels that each got.

#1205 Fixing executing paranoia level counters
  rules/REQUEST-914-FILE-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
Labels: v3.2-dev

#1252 Drop unneeded capture groups and tidy up regexp
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  util/regexp-assemble/regexp-932140.data
Labels: v3.2-dev

#1268 PHP: move get_defined_functions() and friends into PL1
  rules/php-function-names-933150.data
  rules/php-function-names-933151.data
  util/regression-tests/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933150.yaml
Labels: False Negative - Evasion

#1273 Update dockerfile to always use 3.2/dev
  util/docker/Dockerfile
Labels: Testing, docker
